# Generated by Django 5.2.15 on 2026-06-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dim_genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_language', models.CharField(blank=True, default='', max_length=10)),
                ('overview', models.TextField(blank=True, default='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('budget', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='', max_length=500)),
                ('backdrop_url', models.URLField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dim_movies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, default='', max_length=500)),
                ('known_for_department', models.CharField(blank=True, default='', max_length=50)),
                ('popularity', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dim_people',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGenreStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('trending_count', models.IntegerField(default=0)),
                ('avg_popularity', models.FloatField(default=0)),
                ('avg_vote_average', models.FloatField(default=0)),
                ('total_budget', models.BigIntegerField(default=0)),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('avg_roi', models.FloatField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.genre')),
                ('top_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.movie')),
            ],
            options={
                'db_table': 'agg_monthly_genres',
                'ordering': ['-month', '-trending_count'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.movie')),
            ],
            options={
                'db_table': 'bridge_movie_genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, through='trends.MovieGenre', to='trends.genre'),
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='movie', max_length=10)),
                ('week_start', models.DateField()),
                ('days_trending', models.IntegerField(default=0)),
                ('avg_position', models.FloatField(default=0)),
                ('best_position', models.IntegerField(default=0)),
                ('avg_popularity', models.FloatField(default=0)),
                ('popularity_change_pct', models.FloatField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='trends.movie')),
            ],
            options={
                'db_table': 'agg_weekly_summary',
                'ordering': ['-week_start', 'avg_position'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='movie', max_length=10)),
                ('date', models.DateField()),
                ('position', models.IntegerField()),
                ('position_change', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_trends', to='trends.movie')),
            ],
            options={
                'db_table': 'fact_daily_trends',
                'ordering': ['date', 'position'],
                'unique_together': {('movie', 'date', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, default='', max_length=500)),
                ('cast_order', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='trends.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmography', to='trends.person')),
            ],
            options={
                'db_table': 'bridge_movie_cast',
                'ordering': ['cast_order'],
                'unique_together': {('movie', 'person')},
            },
        ),
    ]
